name: Nim Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nim-version: ['1.6.x', '2.0.x']

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        
    - name: Install Dependencies
      run: nimble install -y
      
    - name: Run Tests
      run: nimble test

    - name: Run Tests with ARC
      run: nimble test --gc:arc -y